name: pyenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - setuptools<65
  - gfortran_linux-64>=11.2.0  # For Linux; use gfortran_osx-64=11.2.0 for macOS
  - openblas>=0.3.18            # BLAS and LAPACK for numerical computing
  - ninja>=1.10.2
  - openmpi>=5.0.8
  - cuda=12.6.0
